### ISSUE TITLE
APNS_PRIVATE_KEY as env variable

### ISSUE THREAD

**Issue by alvarow** [arminfelder/RocketChatMobilePushGateway#2]
Hi, how do you set `APNS_PRIVATE_KEY` as an environment variable? That file is multiple lines after converted to .pem...

I tried like this:

```
APNS_PRIVATE_KEY='-----BEGIN EC PRIVATE KEY----- ==big-hash-here== -----END EC PRIVATE KEY-----'
```

but I get signing error...

```
ApplePushModel.cpp:225] signing failed
```

Thanks

**Comment by arminfelder** [comment]
@alvarow have you tried to use '\n' s

**Comment by alvarow** [comment]
I did :-(

For Google I do get:  "Google push conn status: OK"

How do you do it?

Thanks

**Comment by arminfelder** [comment]
For my production setup, I still mount the certificate, but I will investigate on that as soon as I find some time

**Comment by alvarow** [comment]
It’s ok! I took it as a project and wrote my own! thanks anyway
